version: '3.7'
services:
    redis:
        restart: always
        container_name: redis
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - /data/redis-data:/data
    webapi:
        build:
            context: .
        container_name: webapi
        environment:
            - TZ=Asia/Taipei
        restart: always
        ports:
            - 8080:8080
        command: >
            /bin/bash -c "
            sleep 10;
            ./build/main;"
    